USE LEARNING;

SHOW TABLES;

SELECT * FROM TRUE_COST_FAST_FASHION LIMIT 10;

-- HOW MANY UNIQUE BRANDS ARE INCLUDED IN THE DATASET?

WITH TABLE1 AS (SELECT DISTINCT BRAND FROM TRUE_COST_FAST_FASHION)
SELECT COUNT(*) FROM TABLE1 ;

-- WHAT ARE THE AVAILABLE YEARS COVERED IN THE DATASET?

SELECT DISTINCT YEAR FROM TRUE_COST_FAST_FASHION;

-- WHAT IS THE TOTAL PRODUCTION VOLUME FOR EACH BRAND?

SELECT BRAND, ROUND(SUM(MONTHLY_PRODUCTION_TONNES),2) FROM TRUE_COST_FAST_FASHION GROUP BY BRAND;

-- WHICH BRAND HAD THE HIGHEST PRODUCTION IN 2020?

WITH TABLE1 AS (SELECT BRAND AS 'BRAND', SUM(MONTHLY_PRODUCTION_TONNES) AS 'TOTAL_PRODUCTION_IN_2020' FROM TRUE_COST_FAST_FASHION WHERE YEAR = 2020 GROUP BY BRAND)
SELECT BRAND, TOTAL_PRODUCTION_IN_2020 FROM TABLE1 ORDER BY TOTAL_PRODUCTION_IN_2020 DESC LIMIT 1;

-- WHICH BRAND HAS THE HIGHEST AVERAGE CARBON EMISSIONS?

WITH TABLE1 AS (SELECT BRAND, AVG(CARBON_EMISSIONS_TCO2E) AS 'AVG_CO2_EMISSIONS' FROM TRUE_COST_FAST_FASHION GROUP BY BRAND)
SELECT BRAND, AVG_CO2_EMISSIONS FROM TABLE1 ORDER BY AVG_CO2_EMISSIONS DESC LIMIT 1;

-- WHICH BRAND HAD THE LOWEST WATER USAGE IN 2019?

WITH TABLE1 AS (SELECT BRAND, WATER_USAGE_MILLION_LITRES FROM TRUE_COST_FAST_FASHION WHERE YEAR = 2019)
SELECT BRAND, WATER_USAGE_MILLION_LITRES FROM TABLE1 ORDER BY WATER_USAGE_MILLION_LITRES ASC LIMIT 1;

--  WHICH YEAR HAD THE MOST REPORTS OF CHILD LABOR?

WITH TABLE1 AS (SELECT YEAR, SUM(CHILD_LABOR_INCIDENTS) AS 'TOTAL_CHILD_LABOUR_INCIDENTS' FROM TRUE_COST_FAST_FASHION GROUP BY YEAR)
SELECT YEAR, TOTAL_CHILD_LABOUR_INCIDENTS FROM TABLE1 ORDER BY TOTAL_CHILD_LABOUR_INCIDENTS DESC LIMIT 1;

-- WHICH BRAND HAD THE MOST POSITIVE SOCIAL MEDIA SENTIMENT IN 2022?

SELECT BRAND, TOTAL_SENTIMENT FROM (SELECT BRAND, SUM(SENTIMENT_SCORE) AS 'TOTAL_SENTIMENT' FROM TRUE_COST_FAST_FASHION WHERE YEAR = 2022 GROUP BY BRAND HAVING TOTAL_SENTIMENT > 0) AS TABLE1
ORDER BY TOTAL_SENTIMENT DESC LIMIT 1;

-- WHICH COUNTRIES HAVE THE WORST LABOR CONDITIONS ON AVERAGE?

SELECT COUNTRY, AVERAGE_WAGES FROM (SELECT COUNTRY, AVG(AVG_WORKER_WAGE_USD) AS 'AVERAGE_WAGES' FROM TRUE_COST_FAST_FASHION GROUP BY COUNTRY) AS TABLE1 ORDER BY AVERAGE_WAGES ASC LIMIT 1;

-- WHICH BRANDS HAVE REDUCED THEIR CARBON EMISSIONS OVER TIME?

WITH TABLE1 AS(SELECT BRAND, YEAR, SUM(CARBON_EMISSIONS_TCO2E) AS 'TOTAL_CARBON_EMISSION' FROM TRUE_COST_FAST_FASHION GROUP BY YEAR, BRAND),
TABLE2 AS(SELECT BRAND, FIRST_VALUE(TOTAL_CARBON_EMISSION) OVER (PARTITION BY BRAND ORDER BY YEAR) AS EMISSION_START, LAST_VALUE(TOTAL_CARBON_EMISSION) OVER(PARTITION BY BRAND ORDER BY YEAR ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS EMISSION_LAST FROM TABLE1)
SELECT DISTINCT BRAND FROM TABLE2 WHERE EMISSION_LAST < EMISSION_START

-- HOW MANY UNIQUE BRANDS ARE IN THE DATASET?

SELECT DISTINCT BRAND FROM TRUE_COST_FAST_FASHION;

-- WHICH YEARS ARE COVERED IN THE DATASET?

SELECT DISTINCT YEAR FROM TRUE_COST_FAST_FASHION;

-- WHAT IS THE TOTAL PRODUCTION VOLUME FOR EACH BRAND?

SELECT SUM(MONTHLY_PRODUCTION_TONNES) AS TOTAL_VOLUMES, BRAND FROM TRUE_COST_FAST_FASHION GROUP BY BRAND;

-- WHICH COUNTRY HAS THE LOWEST AVERAGE WORKER WAGE?

WITH TABLE1 AS (SELECT COUNTRY, SUM(AVG_WORKER_WAGE_USD) AS AVG_WAGE FROM TRUE_COST_FAST_FASHION GROUP BY COUNTRY)
SELECT COUNTRY, AVG_WAGE  FROM TABLE1 ORDER BY AVG_WAGE ASC LIMIT 1;

-- WHAT IS THE TOTAL PRODUCTION PER BRAND PER YEAR?

SELECT BRAND, SUM(MONTHLY_PRODUCTION_TONNES) AS TOTAL_PRODUCTION, YEAR FROM TRUE_COST_FAST_FASHION GROUP BY BRAND, YEAR ORDER BY YEAR ASC; 

-- WHICH COUNTRY HAD THE HIGHEST CHILD LABOR INCIDENTS IN 2021?

SELECT COUNTRY, SUM(CHILD_LABOR_INCIDENTS) AS TOTAL_CHILD_INCIDENTS FROM TRUE_COST_FAST_FASHION GROUP BY COUNTRY ORDER BY TOTAL_CHILD_INCIDENTS DESC LIMIT 1;

-- WHICH TWO BRANDS HAD NEARLY THE SAME PRODUCTION IN 2022?

WITH TABLE1 AS (SELECT BRAND, SUM(MONTHLY_PRODUCTION_TONNES) AS TOTAL_PRODUCTION FROM TRUE_COST_FAST_FASHION WHERE YEAR = 2022 GROUP BY BRAND)
SELECT T1.BRAND AS BRAND1, T2.BRAND AS BRAND2, ABS(T1.TOTAL_PRODUCTION - T2.TOTAL_PRODUCTION) AS PRODUCTION_DIFF FROM TABLE1 T1 JOIN TABLE1 T2 ON T1.BRAND < T2.BRAND ORDER BY PRODUCTION_DIFF ASC LIMIT 1;


-- WHICH BRANDS HAVE AN AVERAGE WORKER WAGE ABOVE 1000 USD?

SELECT BRAND, AVG(AVG_WORKER_WAGE_USD) AS AVG_WORKER_WAGE FROM TRUE_COST_FAST_FASHION GROUP BY BRAND HAVING AVG(AVG_WORKER_WAGE_USD) > 1000;

