SHOW DATABASES;

USE LEARNING;

SHOW TABLES;

WITH TABLE1 AS (SELECT * FROM TRUE_COST_FAST_FASHION AS TF ORDER BY YEAR DESC LIMIT 10) SELECT * FROM TABLE1;

DESCRIBE TRUE_COST_FAST_FASHION;

SHOW COLUMNS FROM TRUE_COST_FAST_FASHION;

SELECT COUNT(*) FROM TRUE_COST_FAST_FASHION;


CREATE TABLE IF NOT EXISTS OPS_REVIEW_TABLE(CONTENT_RELATION_ID VARCHAR(50), REVIEW_STATUS VARCHAR(50), CONSTRAINT PRIMARY_KEY PRIMARY KEY(CONTENT_RELATION_ID));
INSERT INTO OPS_REVIEW_TABLE (CONTENT_RELATION_ID, REVIEW_STATUS) VALUES ("SAC_1425", "APPROVED");


SELECT * FROM OPS_REVIEW_TABLE;


CREATE TABLE IF NOT EXISTS EMPLOYEE (EMPNAME VARCHAR(50), SALARY INT, RESIDENCE VARCHAR(50), JOB_LOCATION VARCHAR(50), DURATION INT);

ALTER TABLE EMPLOYEE MODIFY COLUMN DURATION VARCHAR(50);

ALTER TABLE EMPLOYEE ADD COLUMN EMPID INT PRIMARY KEY;

INSERT INTO EMPLOYEE (EMPNAME, SALARY, RESIDENCE, JOB_LOCATION, DURATION, EMPID) VALUES ("MADHAV", 400000, "PATNA, BIHAR, 803301", "WHITEFIELD, BANGALORE", "3 YEARS", 12213356);

INSERT INTO EMPLOYEE (EMPNAME, SALARY, RESIDENCE, JOB_LOCATION, DURATION, EMPID) VALUES
("RAHUL", 550000, "KANPUR, UTTAR PRADESH, 208001", "HINJEWADI, PUNE", "2 YEARS", 12213357),
("PRIYA", 720000, "JAIPUR, RAJASTHAN, 302012", "CYBER CITY, GURGAON", "4 YEARS", 12213358),
("AMAN", 480000, "LUCKNOW, UTTAR PRADESH, 226010", "SALT LAKE, KOLKATA", "1 YEAR", 12213359),
("NEHA", 600000, "RANCHI, JHARKHAND, 834001", "HITECH CITY, HYDERABAD", "3 YEARS", 12213360),
("ARJUN", 750000, "CHENNAI, TAMIL NADU, 600042", "ELECTRONIC CITY, BANGALORE", "5 YEARS", 12213361),
("KAVYA", 520000, "BHOPAL, MADHYA PRADESH, 462016", "MG ROAD, INDORE", "2 YEARS", 12213362),
("ROHIT", 680000, "NAGPUR, MAHARASHTRA, 440001", "BKC, MUMBAI", "4 YEARS", 12213363),
("SNEHA", 450000, "PATIALA, PUNJAB, 147001", "PHASE 8, MOHALI", "1 YEAR", 12213364),
("VIJAY", 800000, "SURAT, GUJARAT, 395003", "SG HIGHWAY, AHMEDABAD", "6 YEARS", 12213365),
("ANJALI", 540000, "GUWAHATI, ASSAM, 781001", "DISPUR, GUWAHATI", "3 YEARS", 12213366),
("RAJAT", 610000, "VARANASI, UTTAR PRADESH, 221002", "NOIDA SECTOR 62, NOIDA", "2 YEARS", 12213367),
("DIVYA", 470000, "JODHPUR, RAJASTHAN, 342001", "SCIENCE CITY, AHMEDABAD", "1 YEAR", 12213368),
("KARAN", 900000, "COIMBATORE, TAMIL NADU, 641001", "OMR ROAD, CHENNAI", "7 YEARS", 12213369),
("MEERA", 500000, "DEHRADUN, UTTARAKHAND, 248001", "SECTOR 44, GURGAON", "2 YEARS", 12213370),
("SAHIL", 650000, "AMRITSAR, PUNJAB, 143001", "IT PARK, CHANDIGARH", "4 YEARS", 12213371);


TRUNCATE TABLE EMPLOYEE;
DROP TABLE EMPLOYEE;
SELECT * FROM EMPLOYEE AS E;



-- Create a CTE that selects employee name and salary from the EMPLOYEE table and returns only those employees whose salary is greater than 500000

WITH TEMP_REC AS (SELECT E.EMPNAME, E.SALARY FROM EMPLOYEE E WHERE E.SALARY > 500000)
SELECT * FROM TEMP_REC;


-- Using a CTE, get employee name and job_location, but return only employees who work in "BANGALORE"

WITH TEMP_REC AS (SELECT E.EMPNAME , E.JOB_LOCATION FROM EMPLOYEE E WHERE E.JOB_LOCATION LIKE "%BANGALORE%") SELECT * FROM TEMP_REC;

-- Create a CTE that calculates the average salary of all employees

WITH TEMP_REC AS (SELECT AVG(E.SALARY) FROM EMPLOYEE E) SELECT * FROM TEMP_REC;

-- Use a CTE to find the total salary of employees grouped by job_location

WITH TEMP_REC AS (SELECT CASE
	WHEN E.JOB_LOCATION LIKE "%BANGALORE%" THEN "BANGALORE"
	WHEN E.JOB_LOCATION LIKE "%PUNE%" THEN "PUNE"
	WHEN E.JOB_LOCATION LIKE "%GURGAON%" THEN "GURGAON"
	WHEN E.JOB_LOCATION LIKE "%KOLKATA%" THEN "KOLKATA"
	WHEN E.JOB_LOCATION LIKE "%HYDERABAD%" THEN "HYDERABAD"
	WHEN E.JOB_LOCATION LIKE "%INDORE%" THEN "INDORE"
	WHEN E.JOB_LOCATION LIKE "%MUMBAI%" THEN "MUMBAI"
	WHEN E.JOB_LOCATION LIKE "%MOHALI%" THEN "MOHALI"
	WHEN E.JOB_LOCATION LIKE "%AHMEDABAD%" THEN "AHMEDABAD"
	WHEN E.JOB_LOCATION LIKE "%GUWAHATI%" THEN "GUWAHATI"
	WHEN E.JOB_LOCATION LIKE "%NOIDA%" THEN "NOIDA"
	WHEN E.JOB_LOCATION LIKE "%CHENNAI%" THEN "CHENNAI"
	WHEN E.JOB_LOCATION LIKE "%CHANDIGARH%" THEN "CHANDIGARH"
END AS CITY, e.SALARY FROM EMPLOYEE E) SELECT CITY, AVG(SALARY) FROM TEMP_REC GROUP BY CITY;

